# Generated by Django 5.2.7 on 2025-10-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_blogpost_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_sqft',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(default='Apartment', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
